from distutils.core import setup

setup(
    name='PYMellat',
    version='1',
    packages=['CRM', 'CRM.IBS', 'CRM.RAS', 'CRM.RAS.MK', 'CRM.RAS.MK.routeros_api',
              'CRM.RAS.MK.routeros_api.api_communicator', 'CRM.Core', 'CRM.Core.Mail', 'CRM.Core.Image',
              'CRM.Core.IBSServer', 'CRM.URLS', 'CRM.URLS.logs', 'CRM.URLS.menu', 'CRM.URLS.misc', 'CRM.URLS.page',
              'CRM.URLS.user', 'CRM.URLS.login', 'CRM.URLS.polls', 'CRM.URLS.groups', 'CRM.URLS.notify',
              'CRM.URLS.report', 'CRM.URLS.finance', 'CRM.URLS.service', 'CRM.URLS.traffic', 'CRM.URLS.ip_login',
              'CRM.URLS.dashboard', 'CRM.URLS.equipment', 'CRM.URLS.help_desk', 'CRM.URLS.vip_groups',
              'CRM.URLS.permissions', 'CRM.URLS.configuration', 'CRM.Tools', 'CRM.Tools.Online', 'CRM.Handlers',
              'CRM.Decorators', 'CRM.Exceptions', 'CRM.Processors', 'CRM.Processors.Ajax', 'CRM.Processors.Chat',
              'CRM.Processors.Misc', 'CRM.Processors.User', 'CRM.Processors.User.Lock', 'CRM.Processors.User.Reseller',
              'CRM.Processors.User.FrmUserTypes', 'CRM.Processors.User.DocumentManager', 'CRM.Processors.Group',
              'CRM.Processors.Login', 'CRM.Processors.Polls', 'CRM.Processors.Tower', 'CRM.Processors.Notify',
              'CRM.Processors.PTools', 'CRM.Processors.PTools.Core', 'CRM.Processors.PTools.Core.Users',
              'CRM.Processors.PTools.Core.Charge', 'CRM.Processors.PTools.Core.Charge.Package',
              'CRM.Processors.PTools.Core.Charge.Service', 'CRM.Processors.PTools.SearchUtils',
              'CRM.Processors.PTools.FinanceUtils', 'CRM.Processors.Report', 'CRM.Processors.Finance',
              'CRM.Processors.Finance.Payment', 'CRM.Processors.Finance.Payment.Trace',
              'CRM.Processors.Finance.Payment.Mellat', 'CRM.Processors.Finance.Payment.Parsian',
              'CRM.Processors.Finance.Payment.Pasargad', 'CRM.Processors.Finance.Discounts',
              'CRM.Processors.Finance.Discounts.Package', 'CRM.Processors.Finance.Discounts.Service',
              'CRM.Processors.IPLogin', 'CRM.Processors.PopSite', 'CRM.Processors.Service', 'CRM.Processors.Traffic',
              'CRM.Processors.Calendar', 'CRM.Processors.HelpDesk', 'CRM.Processors.HelpDesk.CallHistory',
              'CRM.Processors.Telegram', 'CRM.Processors.VIPGroup', 'CRM.Processors.Dashboard',
              'CRM.Processors.Equipment', 'CRM.Processors.FileManager', 'CRM.Processors.Configuration',
              'CRM.Processors.Configuration.IBS', 'CRM.Processors.IndicatorBook', 'CRM.Processors.Trasportation',
              'CRM.management', 'CRM.management.commands', 'CRM.templatetags', 'CRM.context_processors'],
    url='https://github.com/sauditore/Python-Mellat',
    license='Apache',
    author='Saeed Auditore',
    author_email='saeed.auditore@gmail.com',
    description='Bank Mellat Python API', requires=['django', 'PythonMagick', 'openpyxl', 'ago', 'khayyam', 'lxml',
                                                    'celery', 'weasyprint', 'IPy']
)
